### PR TITLE
Create Transformer folder

### PR DESCRIPTION
**Pull request by ShriAmogh**

### CODE REVIEW

**Comment by viratzzs** [comment]
Keeping the obvious question aside, how about actually creating a folder and not an extension less file?

**Comment by ShriAmogh** [comment]
ok

**Comment by Chiggy-Playz** [comment]
blud didnt even bother to clone the repo

**Comment by ShriAmogh** [comment]
> blud didnt even bother to clone the repo

dude what u doing here

**Comment by Chiggy-Playz** [comment]
Its a public repo of GDG. I'm a part of GDG. What do you expect?

**Comment by MukalDadhwal** [comment]
Bhai what is the PR ?? 😭😭 MARKING SPAM unless improved

**Comment by Chiggy-Playz** [comment]
BTW, the PR is supposed to do one thing and it fails to even do that (you just created a file not a folder)

**Comment by MukalDadhwal** [comment]
😂😂😂😂

**Comment by ShriAmogh** [comment]
> BTW, the PR is supposed to do one thing and it fails to even do that (you just created a file not a folder)

Everyone, i was kidding :)

**Pull request closed without merging**
